### ISSUE TITLE
Memory access out of bounds in Chrome with DevTools closed

### ISSUE THREAD

**Issue by donalffons** [emscripten-core/emscripten#14391]
Hi,

[Here](https://emscripten-dynamic-library-error-donalffons.vercel.app/demos/polygon) is an example deployment to reproduce the issue. The page is supposed to show a single triangle in 3D (loading times are quite long - a bit of patience is necessary). When opening the page on Chrome with DevTools open, it loads fine. With DevTools closed, it gives the following error in the console:
```
RuntimeError: memory access out of bounds
    at _ZNK12BRep_Builder5RangeERK11TopoDS_Edgeddb (<anonymous>:wasm-function[16678]:0xe2dad2)
    at _ZN16BRepLib_MakeEdge4InitERKN11opencascade6handleI10Geom_CurveEERK13TopoDS_VertexS8_dd (<anonymous>:wasm-function[18874]:0x16290b5)
    at _ZN16BRepLib_MakeEdge4InitERKN11opencascade6handleI10Geom_CurveEEdd (<anonymous>:wasm-function[18878]:0x16296bb)
    at _ZN16BRepLib_MakeEdgeC2ERKN11opencascade6handleI10Geom_CurveEE (<anonymous>:wasm-function[18902]:0x162ac2a)
    at _ZN23BRepBuilderAPI_MakeEdgeC2ERKN11opencascade6handleI10Geom_CurveEE (<anonymous>:wasm-function[19445]:0x165b62a)
    at <anonymous>:wasm-function[3213]:0x122de9f
    at _ZN10emscripten8internal7InvokerIP27BOPAlgo_AlertBadPositioningJRK12TopoDS_ShapeEE6invokeEPFS3_S6_EPS4_ (<anonymous>:wasm-function[1951]:0x1220aa2)
    at BRepBuilderAPI_MakeEdge_24.constructor_body (http://localhost:3005/occScript.worker.worker.js:10703:31)
    at BRepBuilderAPI_MakeEdge_24.<anonymous> (http://localhost:3005/occScript.worker.worker.js:10490:23)
    at new BRepBuilderAPI_MakeEdge_24 (eval at createNamedFunction (http://localhost:3005/occScript.worker.worker.js:9516:14), <anonymous>:4:34)
```

This problem has been reproduced with two different system configurations:

- fedora 30 linux, chrome version is 89.0.4389.90 (Official Build) (64-bit)
- manjaro linux, chrome version 90.0.4430.212 (Official Build) (64-bit)

The example is using dynamic modules. I have tried different settings for `-sINITIAL_MEMORY`. `-sALLOW_MEMORY_GROWTH` is enabled.

The issue doesn't seem to appear in Firefox. It was originally reported [here](https://github.com/donalffons/opencascade.js-examples/issues/22).

**Comment by sbc100** [comment]
If the problem only shows up with devtools closed then we have a very odd issue indeed.  Seems like it must either be bug in v8 or some kind of timing issue (or other non-determinism).

Can you try building and running `-fsanitize=address`?

**Comment by donalffons** [comment]
Will do!

**Comment by donalffons** [comment]
Hmm, that argument gives me
```
emcc: error: ASan does not support dynamic linking
```
Full build command
```
'emcc',
'-s', 'MAIN_MODULE=1',
'-s', 'EXPORT_ES6=1',
'-s', 'USE_ES6_IMPORT_META=0',
'-s', 'USE_FREETYPE=1',
'-s', 'EXPORTED_RUNTIME_METHODS=["FS"]',
'-DIGNORE_NO_ATOMICS=1',
'-frtti',
'-fPIC',
'-DHAVE_RAPIDJSON',
'-fsanitize=address',
'-s', 'DISABLE_EXCEPTION_CATCHING=1',
'-O3',
'-s', 'ALLOW_MEMORY_GROWTH=1',
'-s', 'MAXIMUM_MEMORY=4GB',
'--bind',
# Inputs
'-o', '/opencascade.js/dist/opencascade.js'
```

**Comment by donalffons** [comment]
Hmm, I currently don't have an "equivalent" build handy, i.e. a build that contains exactly the same inputs and bindings (remember that we talked about my 30 hour build times? I still haven't gotten around to modifying the build system yet).
I do have another example app (step file tool), which is using a much smaller build of the library without using dynamic libraries (i.e. no `-sMAIN_MODULE`, no `-sSIDE_MODULE` and no `-fPIC`), here: https://interactive-cad-tool.web.app/ .

Hmm, if its of any for this issue, I could
1. Make another 30 hour build of the entire library (with or without `-fsanitize=address`?!)
2. Make a build of the "step file tool" example app with `-fsanitize=address`

(An example STEP file is attach, if you want to try the example app - but that's off topic I guess :wink:)

[ROCKET WOOD v6.step.txt](https://github.com/emscripten-core/emscripten/files/6610596/ROCKET.WOOD.v6.step.txt)

**Comment by sbc100** [comment]
There is no guarantee that `-fsanitize=address` will actually point is to the problem, so it might be worth instead investing time in improving that build time.

In order to track down a heisenbug like this it is useful to be able to try to reduce the test case, by removing build flags and shrinking the size of the your program to make a smaller reproducer.   If your build time is 30 hours this is going to hinder that process :-/

**Comment by donalffons** [comment]
Heisenbug :laughing:. That's a pretty accurate description...
OK, well, I will work on improving the build system then. That way, we might find a solution before the end of the decade. Will post an update when I make some progress.

**Comment by donalffons** [comment]
...just a note: I actually made a "full" build of the library, which finished this morning and it runs without issues (no matter if DevTools are open or closed).

**Comment by cgauld** [comment]
We're investigating a similar heisenbug in Chrome 91 on Android where memory contents are somehow corrupted after heap growth (from `-s ALLOW_MEMORY_GROWTH`). We get various errors immediately after the heap grows, including `RuntimeError: memory access out of bounds` and `Invalid function pointer '0' called with signature ‘iiii’.` The issue doesn't manifest itself with the Chrome debugger open :-/

**Comment by cgauld** [comment]
Ok I have a minimal test case for this issue. TLDR (and unless there's a bug in my test case 😂) I believe there to be a pretty nasty v8 issue as @sbc100 suspected.

I've performed the following test with the current Google Play version of Chrome (91.0.4472.88) on a OnePlus Nord.

Here's my test case:
```cpp
#include <iostream>

int main() {
    size_t amount = 50 * 1024 * 1024; // 50mb

    std::cout << "Creating first allocation - no heap increase should be triggered" << std::endl;

    // Allocate a chunk of memory
    uint8_t * data0 = (uint8_t*)malloc(amount);

    // And populate it with predictable data
    for (int i = 0; i < amount; i++) {
        data0[i] = i % 255;
    }

    std::cout << "Creating second allocation - heap increase" << std::endl;

    // Do the same with another chunk
    uint8_t * data1 = (uint8_t*)malloc(amount);
    for (int i = 0; i < amount; i++) {
        data1[i] = i % 255;
    }

    std::cout << "Verifying first allocation" << std::endl;

    for (int i = 0; i < amount; i++) {
        if (data0[i] != (i % 255)) {
            std::cout << "DATA CHANGED!" << std::endl;
        }
    }

    std::cout << "Verifying second allocation" << std::endl;

    for (int i = 0; i < amount; i++) {
        if (data1[i] != (i % 255)) {
            std::cout << "DATA CHANGED!" << std::endl;
        }
    }

    return 0;
}
```
Which I  compile like this:
```sh
emcc \
    -O2 -s ASSERTIONS=2 \
     -s INITIAL_MEMORY=64mb -s ALLOW_MEMORY_GROWTH=1 -g \
     main.cpp -o index.html
```
Since the initial memory size is 64mb, and code performs two 50mb allocations, there's a heap resize between them.

When the Chrome debugger is open, things work correctly - here's the log:
```
(index):1237 Creating first allocation - no heap increase should be triggered
(index):1237 Creating second allocation - heap increase
index.js:1835 Heap resize call from 67108864 to 110166016 took 8.599999994039536 msecs. Success: true
(index):1237 Verifying first allocation
(index):1237 Verifying second allocation
```
*However* when it's run without the debugger, it fails (without even reaching the verify step) logging the following:
```
(index):1237 Creating first allocation - no heap increase should be triggered
(index):1237 Creating second allocation - heap increase
index.js:1835 Heap resize call from 67108864 to 110166016 took 6.200000002980232 msecs. Success: true
(index):1246 exception thrown: RuntimeError: memory access out of bounds,RuntimeError: memory access out of bounds
    at std::__2::basic_ostream<char, std::__2::char_traits<char> >::sentry::sentry(std::__2::basic_ostream<char, std::__2::char_traits<char> >&) (https://192.168.1.10:8082/index.wasm:wasm-function[1271]:0x1cc3e)
    at std::__2::basic_ostream<char, std::__2::char_traits<char> >& std::__2::__put_character_sequence<char, std::__2::char_traits<char> >(std::__2::basic_ostream<char, std::__2::char_traits<char> >&, char const*, unsigned long) (https://192.168.1.10:8082/index.wasm:wasm-function[14]:0x111f)
    at __original_main (https://192.168.1.10:8082/index.wasm:wasm-function[13]:0xf3b)
    at main (https://192.168.1.10:8082/index.wasm:wasm-function[16]:0x134f)
    at https://192.168.1.10:8082/index.js:1512:22
    at callMain (https://192.168.1.10:8082/index.js:5124:15)
    at doRun (https://192.168.1.10:8082/index.js:5194:23)
    at https://192.168.1.10:8082/index.js:5205:7
printErr @ (index):1246
index.js:38 Uncaught RuntimeError: memory access out of bounds
    at std::__2::basic_ostream<char, std::__2::char_traits<char> >::sentry::sentry(std::__2::basic_ostream<char, std::__2::char_traits<char> >&) (index.wasm:0x1cc3e)
    at std::__2::basic_ostream<char, std::__2::char_traits<char> >& std::__2::__put_character_sequence<char, std::__2::char_traits<char> >(std::__2::basic_ostream<char, std::__2::char_traits<char> >&, char const*, unsigned long) (index.wasm:0x111f)
    at __original_main (index.wasm:0xf3b)
    at main (index.wasm:0x134f)
    at index.js:1512
    at callMain (index.js:5124)
    at doRun (index.js:5194)
    at index.js:5205
```

This is obviously a pretty serious and gnarly issue. I'm going to post it onto the V8 issue tracker too. I think the only workaround for us will be to use a fixed memory allocation rather than allow the heap to grow. Let me know if you have any thoughts!

**Comment by donalffons** [comment]
@cgauld, I can reproduce that issue with your test case on my Samsung Galaxy Note 10+ with the Chrome version you mentioned (91.0.4472.88).
On the same device, it's running fine with Firefox and Firefox Nightly. Strangely, it also seems to be running fine with Chrome Canary.

**Comment by cgauld** [comment]
Posted a v8 bug too: https://bugs.chromium.org/p/v8/issues/detail?id=11863

**Comment by donalffons** [comment]
My package manager just offered updates for Chrome (91.0.4472.101 (Official Build) (64-bit)) and Chrome Dev / Canary (93.0.4535.3 (Official Build) dev (64-bit)).

Both @cgauld's and my test case do not show the problematic behavior in these updated versions and work just fine.

I'm still curious to know if a fix for this issue has been implemented in V8... However, to me it seems like this (Emscripten-related) issue is resolved, now.

**Comment by kripken** [comment]
Yes, I am almost certain there was a v8 ARM bug that has been fixed given the discussion here and in the issue. Would be nice if someone confirms it for us there. Looking through the v8 commits might also be a way to verify (something with turbofan and ARM in the title), if someone is curious and has time.

In any case, I agree this issue can be fixed, and we can follow updates in the v8 issue (thanks for filing that!)

**Comment by tangobravo** [comment]
I've just received the android 91.0.4472.101 32-bit build on my Pixel 4A and unfortunately I can still reproduce the issue with the minimal test cases in the v8 bug report.

Just posting here for info - think it's right to keep this one closed and assume it's a v8 bug for now unless we hear otherwise.
