### ISSUE TITLE
--preload-file error message is not instructive

### ISSUE THREAD

**Issue by rodrigob** [emscripten-core/emscripten#2656]
Trying to add a `--preload-file` to my emscripten project, I receive

```
Error: Embedding "./file_or_interest.bin" which is below the current directory "path_of_source_code/emscripten_build". This is invalid since the current directory becomes the root that the generated code will see
```

The error message is unclear for newcomers since it does not instruct for the recommended procedure ("so this does not work, what should I try now ?").

The command line I am using is

```
em++ my_big_library.a -s EXPORTED_FUNCTIONS="['_function_of_interest']" --preload-file ./file_or_interest.bin  -o test.html
```

Thanks for suggestion of "what to do ?"

**Comment by silenthell** [comment]
> 
> 
> Using `./` or not makes no difference, both raise the same error message.
> Using a directory as input to `--preload-file` works (should be renamed `--preload-directory` ?), which is consistent with http://kripken.github.io/emscripten-site/docs/packaging/Filesystem-Guide.html#packaging-files

Here on windows (and without symlink) if I specify a file below the build directory it will throw this error, however, for a directory it works just fine... It really is just the matter of passing:
````
     --embed-file ../samples/
````
Instead of:
````
     --embed-file ../samples/my_file.ext
````

**Comment by royalstream** [comment]
May 2022. I was having the same issue. Here's how I fixed it:

- I noticed that [file_packager.py only raises this error after checking for `if not file_.explicit_dst_path`](https://github.com/kripken/emscripten/blob/master/tools/file_packager.py#L443)
- Then I noticed that [`explicit_dst_path` seems to be related to `uses_at_notation`](https://github.com/kripken/emscripten/blob/master/tools/file_packager.py#L399)

Looking at the [latest documentation for the File Packager](https://emscripten.org/docs/porting/files/packaging_files.html)  it says that:
> The @ symbol is needed because sometimes it is useful to package files that are not nested below the compile-time directory, and for which there is therefore no default mapping to a location in the virtual file system.

So, in my particular case I simply changed `--preload-file ../images/` to `--preload-file ../images@/` and it worked like a charm.

**Comment by allsey87** [comment]
I am still seeing the same issue with both `--embed-file` and `--preload-file` in Emscripten 3.1.14. I have tried using both symlinks and real files as well as putting the file into a directory called assets and moving that directory to different locations on the file system, but always the same uninformative error...

```
Error: Embedding "/workspaces/emscripten_linking/src/code/triple_two_runtime/assets/libtriple.so" which is below the current directory "/workspaces/emscripten_linking/build/triple_two_runtime". This is invalid since the current directory becomes the root that the generated code will see
emcc: error: '/opt/emsdk/upstream/emscripten/tools/file_packager triple_two_runtime.data --from-emcc --export-name=Module --preload /workspaces/emscripten_linking/src/code/triple_two_runtime/assets/libtriple.so' failed (returned 1)
make[2]: *** [CMakeFiles/triple_two_runtime.dir/build.make:84: triple_two_runtime.html] Error 1
make[1]: *** [CMakeFiles/Makefile2:137: CMakeFiles/triple_two_runtime.dir/all] Error 2
make: *** [Makefile:129: all] Error 2
```

**Comment by sbc100** [comment]
> "below" ? you mean "above", right ? Seems like this issue is rather fixable. I am just not sure where in the code it should be fixed.

I think this is the root (no pun intended) of the problem.   The terms "below" and "under" normally mean "contained with" or "lower down in the tree" in filesystem terminology.  I think this error message has it backwards.   

I've trying to address that here https://github.com/emscripten-core/emscripten/pull/17599
