### ISSUE TITLE
Add support for C++11 thread_local and GNU __thread modifiers.

### ISSUE THREAD

**Issue by juj** [emscripten-core/emscripten#3502]
Currently the pthreads implementation only supports TLS variables via the good old `pthread_get/setspecific` API. Investigate how to add support for the C/C++ modifiers `thread_local_` and `__thread` to do the same thing.

See https://gcc.gnu.org/onlinedocs/gcc-3.4.1/gcc/Thread-Local.html and http://en.cppreference.com/w/cpp/language/storage_duration

**Comment by juj** [comment]
It can also be possible to optimize these in the way that https://github.com/kripken/emscripten/issues/3504 refers to.

**Comment by OleksandrChekhovskyi** [comment]
So `__thread` keyword does not work, but is accepted by compiler without any warning. That was an easily preventable debugging session. I would like to suggest making these keywords throw errors (like on iOS, where they are also not supported).

**Comment by VirtualTim** [comment]
This has actually been fixed by #8976, so `wontfix` should be removed.
@kripken.

**Comment by tlively** [comment]
In case anyone finds this and expects thread-locals to work: They work with the upstream backend (now the default), but they still do not and will never work with the old Fastcomp backend.
