### ISSUE TITLE
Memory grows each time the page refresh : Uncaught RangeError: WebAssembly.Memory(): could not allocate memory

### ISSUE THREAD

**Issue by pierreglibert** [emscripten-core/emscripten#8126]
Hi community :)
I get an error after several refresh : Uncaught RangeError: WebAssembly.Memory(): could not allocate memory.

When I go to "inspect > memory > Select Javascript VM instance", memory grows each time I refresh the page.
When memory is bigger than 40mo, the error appear.
How can I clear memory on refresh page ?
The memory should not be deleted automatically ?

Thanks in advance for your help ;)

**Comment by kripken** [comment]
The browser should clear the memory, but may take time until it garbage collects it. So this could be a browser bug, or at least something the browser could do better. Which browser is it on? We should file a bug with a testcase.

**Comment by luisfonsivevo** [comment]
I'm getting the same problem on Chrome 72 Linux with the latest Ammo build. After 36 refreshes (probably arbitrary, but in my project it's always the same number) I get the error:

```
Uncaught RangeError: WebAssembly.Memory(): could not allocate memory
    at ammo.wasm.js:formatted:175
    at main ((index):82)
    at onload ((index):17)
```

Which is just the memory module constructor:

```
new WebAssembly.Memory({
    initial: Aa / 65536,
    maximum: Aa / 65536
})
```

Looking into a heap snapshot shows the full story:
![](https://i.imgur.com/EgnYXkI.png)

Chrome isn't fully resetting the heap! Clicking the garbage collection button doesn't help, either. Firefox doesn't have this issue so it's probably just a Chrome bug. It's also worth noting that I can't get the same effect when manually creating a memory object in the console.

**Comment by pierreglibert** [comment]
@luisfonsivevo @kripken thanks for your reply :)

I'm on macOs 10.14.3, google chrome 72.0.3626.109.
I'm agree with you, firefox work fine. It's a chrome bug.

Chrome capture :
![capture d ecran 2019-02-24 a 10 23 29](https://user-images.githubusercontent.com/21291915/53297493-cadaf680-381f-11e9-9abe-c5ed1f40f31e.png)
![capture d ecran 2019-02-24 a 10 24 27](https://user-images.githubusercontent.com/21291915/53297495-cadaf680-381f-11e9-85c5-3115764f7d20.png)

Where can we create an issue for google chrome ?

**Comment by luisfonsivevo** [comment]
@pierreglibert Here's a link to [Chromium's official bug tracker](https://bugs.chromium.org/p/chromium/issues/list)

**Comment by pierreglibert** [comment]
@luisfonsivevo done :)

**Comment by pierreglibert** [comment]
... I have this with firefox, but memory does not seem to grow : � 
<img width="875" alt="capture d ecran 2019-02-24 a 16 24 21" src="https://user-images.githubusercontent.com/21291915/53301256-c549d480-3850-11e9-94f1-b9fff60461d1.png">

It show "exceeded 16 live ..." exactly after 16 page refreshes...

**Comment by kripken** [comment]
@pierreglibert do you have a link to the bug you filed? I can try to cc some relevant people to speed things up.

**Comment by luisfonsivevo** [comment]
@kripken I was able to find it last night before it got too buried. https://bugs.chromium.org/p/chromium/issues/detail?id=935169&q=&colspec=ID%20Pri%20M%20Stars%20ReleaseBlock%20Component%20Status%20Owner%20Summary%20OS%20Modified

**Comment by pierreglibert** [comment]
Last test : 
• Safari 12.0.3 works 👍 
• Opera 58.0.3135.68 works 👍 
• Firefox 65.0.1 works **BUT** show warning after 16 refresh 👎 

> Error: WebGL warning: <SetDimensions>: Exceeded 16 live WebGL contexts for this principal, losing the least recently used one.

• Chrome 72.0.3626.119 works **BUT** show error after several refresh 👎 

> Uncaught RangeError: WebAssembly.Memory(): could not allocate memory

**Comment by kripken** [comment]
Thanks @luisfonsivevo! Looks like it's already being prepared for triage, good.

**Comment by pierreglibert** [comment]
Here a sample : 
[triangle.zip](https://github.com/emscripten-core/emscripten/files/2904857/triangle.zip)

**Comment by pierreglibert** [comment]
> I played around with this some more and found that it only happens when DevTools is open. Once I close DevTools I can refresh the page as normal and the memory is properly freed. Memory won't start growing again until DevTools reopens and the page is refreshed.

> I confirm, it's only appear when devTool is open.
Thanks @jerbear.

[I confirm, it's only appear when devTool is open.
Thanks @jerbear.](url)

**Comment by mmontag** [comment]
Wow, another confirmed case here. 
I started to go crazy walking back changes to my build before I finally Googled this error. Good work @pierreglibert

**Comment by iooops** [comment]
Is there any way to solve it?

**Comment by luisfonsivevo** [comment]
Currently the only way to fix this (in Chromium) is to close dev tools and then refresh the page. Normal users won't have a problem because this bug is only related to dev tools. Still not fixed yet as of 73.

As for for Firefox, I haven't been able to reproduce it.

**Comment by nicksen782** [comment]
I also encounter this issue at the 36th load and it is consistent. However, I encounter it with or without Dev tools open. This is the loading portion of my program where I start each instance. (I last updated my copy of Emscripten on 2019-03-22.)

// Remove the Module.
emu.vars.innerEmu.Module=null;

// Wait 500 ms.
setTimeout(function(){
 // Reset Module to the defaults settings.
 emu.vars.innerEmu.Module = new emu.vars.innerEmu.createDefaultModule();

 // Edit Module: Set the game file.
 emu.vars.innerEmu.Module.arguments = [emu.vars.gameFile];

 try{
  // Start the new instance.
  emu.vars.innerEmu.UOP( emu.vars.innerEmu.Module );
 }
  catch(e){ console.log("The emulator failed to load. Please refresh this web page.", e); }
}, 500);

**Comment by vanjavk** [comment]
Bug is still present (I use webgl2 in my files). Simple triangle drawing.

> Last test :
> • Safari 12.0.3 works 👍
> • Opera 58.0.3135.68 works 👍
> • Firefox 65.0.1 works **BUT** show warning after 16 refresh 👎
> 
> > Error: WebGL warning: : Exceeded 16 live WebGL contexts for this principal, losing the least recently used one.
> 
> • Chrome 72.0.3626.119 works **BUT** show error after several refresh 👎
> 
> > Uncaught RangeError: WebAssembly.Memory(): could not allocate memory

For me this is incorrect.
It doesn't work either in current latest Chrome❌ (>than your version) and Opera❌(>than your version). Which would make sense because Opera is based on Chromium.

However in Firefox it works fine.
Firefox: 67.0.4 (64-bit) ✔

After every refresh snapshot says memory is about same and is not increasing. Unlike on both chrome and opera where after about 30 refreshes memory reaches certain amount (seems to be 600MB?) and doesn't want to load anymore

**Comment by kripken** [comment]
There are some known issues with the chrome devtools and with pthreads on chrome. If this isn't related to either of those, then a testcase would be good, as this may be an unknown bug.

**Comment by vanjavk** [comment]
Actually this seems to be a problem with **chrome devtools**. If I close and reopen devtools memory is reset, and app is loading fine.

I also wasn't able to reproduce this bug when **not** using chrome devtools.

**Comment by pierznj** [comment]
Aaaand one more here, also using Opencv.js...

**Comment by clapragr** [comment]
+1 I am having the same issue

**Comment by Rainy-Bear** [comment]
Same issue here: I've got an WebAssembly.Memory(): could not allocate memory error after refreshing a page that imports and initializes a quite heavy webassembly; I'm using Chrome  78.0.3904.108

**Comment by kripken** [comment]
As mentioned a few comments back: there are known issues with devtools, and known issues with pthreads (although I think the pthreads ones were fixed in latest stable). If you see this without either of those, then please provide a testcase, as that may be an unknown issue.

**Comment by Junior2Ran** [comment]
Chrome 83，still not fixed.
Is there a way that I can free the memory by hand? Like memeory.destory() or something?

**Comment by JuniorTour** [comment]
Win 10 && Chrome 92, still has this error: WebAssembly.Memory(): could not allocate memory

Does it relate to [`SharedArrayBuffer` was removed from Chrome API](https://developer.chrome.com/blog/enabling-shared-array-buffer)?

**Comment by NtLoadDriverEx** [comment]
Still present in Version 140.0.7323.0 (Official Build) canary (64-bit). 2025 
and Version 138.0.7204.169 (Official Build) (64-bit).
