### ISSUE TITLE
LTO flags with wasm backend

### ISSUE THREAD

**Issue by kripken** [emscripten-core/emscripten#8574]
Discussing with @aardappel, a few things seem incomplete in our LTO support with the wasm backend. The only way it works right now is to pass `-s WASM_OBJECT_FILES=0` for each compilation to object, and also at link time, and to also add `--llvm-lto 1` at link time as well. However,

1. Perhaps `-flto` should turn on `-s WASM_OBJECT_FILES=0`?
2. Perhaps `--llvm-lto 1` should do the same? And also work when compiling to an object file?
3. Perhaps we should deprecate the `--llvm-lto 2/3` modes, as those don't work with the wasm backend - do we still want them? (they run more llvm opts than the standard llvm-link-opts)

A related issue is that building an object file with `-s WASM_OBJECT_FILES=0` and linking it without that flag will fail, I'm not sure if that's expected to work or not? E.g.

```
$ ./emcc tests/hello_libcxx.cpp -O3 -s WASM_OBJECT_FILES=0 -c -o a.o
$ ./emcc a.o -O3
wasm-ld: warning: function signature mismatch: _ZNSt3__215basic_streambufIcNS_11char_traitsIcEEE7seekposENS_4fposI11__mbstate_tEEj
>>> defined as () -> void in /usr/local/google/home/azakai/.emscripten_cache/wasm-obj/libc++_noexcept.a(iostream.cpp.o)
>>> defined as (i32, i32, i32, i32) -> void in /usr/local/google/home/azakai/.emscripten_cache/wasm-obj/libc++_noexcept.a(ios.cpp.o)

wasm-ld: warning: function signature mismatch: _ZNSt3__215basic_streambufIcNS_11char_traitsIcEEE7seekoffExNS_8ios_base7seekdirEj
>>> defined as () -> void in /usr/local/google/home/azakai/.emscripten_cache/wasm-obj/libc++_noexcept.a(iostream.cpp.o)
>>> defined as (i32, i32, i64, i32, i32) -> void in /usr/local/google/home/azakai/.emscripten_cache/wasm-obj/libc++_noexcept.a(ios.cpp.o)

wasm-ld: warning: function signature mismatch: _ZNSt3__215basic_streambufIwNS_11char_traitsIwEEE7seekposENS_4fposI11__mbstate_tEEj
>>> defined as () -> void in /usr/local/google/home/azakai/.emscripten_cache/wasm-obj/libc++_noexcept.a(iostream.cpp.o)
>>> defined as (i32, i32, i32, i32) -> void in /usr/local/google/home/azakai/.emscripten_cache/wasm-obj/libc++_noexcept.a(ios.cpp.o)

wasm-ld: warning: function signature mismatch: _ZNSt3__215basic_streambufIwNS_11char_traitsIwEEE7seekoffExNS_8ios_base7seekdirEj
>>> defined as () -> void in /usr/local/google/home/azakai/.emscripten_cache/wasm-obj/libc++_noexcept.a(iostream.cpp.o)
>>> defined as (i32, i32, i64, i32, i32) -> void in /usr/local/google/home/azakai/.emscripten_cache/wasm-obj/libc++_noexcept.a(ios.cpp.o)
error: undefined symbol: _ZNSt3__216__pad_and_outputIcNS_11char_traitsIcEEEENS_19ostreambuf_iteratorIT_T0_EES6_PKS4_S8_S8_RNS_8ios_baseES4_
warning: To disable errors for undefined symbols use `-s ERROR_ON_UNDEFINED_SYMBOLS=0`
Error: Aborting compilation due to previous errors
```

**Comment by kripken** [comment]
cc @sbc100

**Comment by sbc100** [comment]
Yup.  This is a known (to me anyway) issue.  Thanks for filing a bug about it.

**Comment by steven-johnson** [comment]
(not really related, but: what's up with the `wasm-ld: warning: function signature mismatch: _ZNSt3__215basic_streambufIcNS_11char_traitsIcEEE7seekposENS_4fposI11__mbstate_tEEj` warnings? I see that in my builds too, and it doesn't seem to do any harm, but it is a lot of buildspam. Known issue?)

**Comment by sbc100** [comment]
Yes: https://bugs.llvm.org/show_bug.cgi?id=40412.  There is a fix in flight on the llvm side which should hopefully land in the next day or so.

**Comment by rahulchaphalkar** [comment]
Any idea about the status of this issue - is it fixed?

**Comment by kripken** [comment]
I believe so, that bug has been closed a while ago. @rahulchaphalkar do you still see the problem on the latest version?

**Comment by rahulchaphalkar** [comment]
ah yes, it seems to have been fixed. I got confused with the above mentioned warnings, which i'm getting, but looks like they are harmless. I'm facing another issue, i'll open a new issue for that. Thanks.

**Comment by niekvlessert** [comment]
Maybe I'm doing something wrong but when building I get 
```
wasm-ld: warning: function signature mismatch: gzseek
>>> defined as (i32, i32, i32) -> i32 in libvgmplay.a(VGMPlay_8cb594a0.c.o)
>>> defined as (i32, i64, i32) -> i64 in /root/.emscripten_cache/wasm-obj/libz.a(gzlib_667366dc.c.o)
```

And when gzseek is used I get 
```Uncaught TypeError: F is not a function```

When using WASM_OBJECT_FILES=0 the errors during building will disappear but gzseek function still isn't working.
